# Parameters
KP: '4'                # attractive potential gain
ETA: '100.0'             # repulsive potential gain
AREA_WIDTH: '2'      # potential area width [m]

# the number of previous positions used to check oscillations
OSCILLATIONS_DETECTION_LENGTH: '3'

Maximun_distance: 9   #Distance in meters to search free space and calculate paths 
